#version: "3"
#services:
#  springapp:
#    build: .
#    container_name: springapp
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#    ports:
#      - 8000:8080
#    restart: always
#    depends_on:
#      - db
#  db:
#    image: postgres:14
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=12345
#      - POSTGRES_DB=postgres
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    ports:
#      - 5000:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    restart: always
#volumes:
#  pgdata:


version: "3.9"
services:
  webapp:
    build: .
    container_name: webapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: postgresql://postgres:12345@db:5432/postgres?sslmode=disable
    links:
      - db
      - prometheus

volumes:
  pgdata: